from __future__ import annotations
from typing import Protocol, Iterable, Optional
from .task import Task


class TaskRepository(Protocol):
    """Contrat d'accès aux données (Repository pattern)."""

    def all(self) -> Iterable[Task]: ...
    def get(self, task_id: str) -> Optional[Task]: ...
    def save(self, task: Task) -> None: ...
    def delete(self, task_id: str) -> bool: ...
